# Generated by Django 3.0.7 on 2020-06-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('withdraw', 'withdrawn'), ('draft', 'draft')], default='draft', max_length=10),
        ),
    ]
